### ISSUE TITLE
An error occurs ' 'ValueError: too many values to unpack (expected 3)'

### ISSUE THREAD

**Issue by jhq1234** [lannguyen0910/deep-efficient-person-reid#2]
An error occurs ' 'ValueError: too many values to unpack (expected 3)'

When I run a code 'python train.py --config_file=resnet50_cuhk', the train starts successfully but at the end, after 50 epoch, an error occurs like this 'ValueError: too many values to unpack (expected 3)'
How can I solve this problem?

**Comment by lannguyen0910** [comment]
Hi @jhq1234, thank you for reporting this issue, the evaluation session when training was missing some return values so that it caused the error which you might have experienced. I have fixed this error recently and updated the notebook, you can follow the instructions for better experience in training and testing.
