### ISSUE TITLE
Pretrained Models (on ImageNet) EfficientNet-v2 link not good 

### ISSUE THREAD

**Issue by mbenami** [lannguyen0910/deep-efficient-person-reid#3]
Hi thanks for sharing this repo 
I try to load the EfficientNet-v2 ImageNet weights 
but there is no net or model in the file

**Comment by lannguyen0910** [comment]
Hi @mbenami, thanks for asking the question. You could try the script below to download the Efficientnet-v2 ImageNet weight
```
!gdown https://drive.google.com/uc?id=1rTYuStYA64U1qb7uC-h8DOhv99Ztxaxz
```

And if you want to load it, you should change 2 lines in either "efficientnetv2_market.yaml" or "efficientnetv2_cuhk.yaml" to:
```
pretrain_path: "efficienetv2_imagenet.pt"
pretrain_choice: "imagenet"
```

I suggest that you should follow the instructions in the notebook i attached in README. If you come up with any errors or issues, please reach out to me soon. Thank you!

**Comment by mbenami** [comment]
Hi @lannguyen0910 
thanks for the quick response 
still when I try to load the weight I get an error 

load weights 
```
torch.load("efficienetv2_imagenet.pt")
```
error:
```
ModuleNotFoundError: No module named 'nets'
```

you can also see there is not weights in the file :
`https://drive.google.com/file/d/1rTYuStYA64U1qb7uC-h8DOhv99Ztxaxz/view`

**Comment by lannguyen0910** [comment]
Hi @mbenami, have you tried changing 2 lines in the yaml file and run it? If you follow the instructions in the colab notebook, you shouldn't get any errors in loading the weight, although some ```gdown``` lines are inaccessible now but you can still download the ```market1501``` dataset and ```efficienetv2_imagenet.pt``` weight.

If you didn't run the notebook, can i ask where is the specific file you place```torch.load("efficienetv2_imagenet.pt")``` line? Because the code itself doesn't have that line, you can take a look at line 153 and 201 in ```nets/nn.py``` for more information.

Besides, when i click in the weight link, i can still download the weight, here are some images:

![image](https://user-images.githubusercontent.com/47696901/125011283-5ae90600-e092-11eb-82a7-89a1258ed2b7.png)

![image](https://user-images.githubusercontent.com/47696901/125011469-b9ae7f80-e092-11eb-837b-c20bb8fe70be.png)
